name: Deploy Backend

on:
  push:
    branches:
      - main
      - chore/update-workflows
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-frontend.yaml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        working-directory: ./backend
        run: pnpm install --frozen-lockfile

      - name: Build project
        working-directory: ./backend
        run: pnpm build

      - name: Copy built files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "backend/*"
          target: ${{ vars.BACKEND_DEPLOY_DIR }}
          strip_components: 1

      - name: Start server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            cd ${{ vars.BACKEND_DEPLOY_DIR }}
            echo "FRONTEND_URL=${{ vars.FRONTEND_BASE_URL }}" > .env
            pm2 start ecosystem.config.js


