name: Deploy Frontend

on:
  push:
    branches:
      - main
      - chore/update-workflows
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yaml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Build project
        working-directory: ./frontend
        run: tsc && VITE_API_BASE_URL=${{ vars.API_BASE_URL }} vite build

      - name: Copy built files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "frontend/dist/*"
          target: ${{ vars.DEPLOY_DIR }}
          strip_components: 1
